export default [
    {
        id : 0,
        title : "Scrum (Desenvolvimento de Software)",
        area: "Tecnologias",
        definition: "é um framework de gerenciamento de projetos, da organização ao desenvolvimento ágil de produtos complexos e adaptativos com o mais alto valor possível, através de várias técnicas.",
        objective: "Profissional",
        description : "O \"Professional Scrum Trainer\" (PST) é um título concedido pela Scrum.org a profissionais que demonstram profundos conhecimentos práticos e teóricos sobre o Framwork Scrum e que são aprovados em um rigoroso e extenso processo seletivo para tal. O título de PST representa a mais alta honraria e reconhecimento dentro da comunidade Scrum e seus portadores são reconhecidos como verdadeiras autoridades na adoção, implementação e uso do Scrum e suas práticas complementares em empresas, governos e organizações.",
        references: 'Sim',
    },
    {
        id: 1,
        title: "Relações Interpessoais",
        area: "Recursos Humanos",
        definition: "O conceito de relacionamento interpessoal se dá pela interação entre duas ou mais pessoas. A todo momento estamos interagindo, seja em casa, na comunidade, no ambiente social e principalmente no ambiente de trabalho.",
        objective: "Profissional",
        description: "É a forma como as pessoas se relacionam e interagem dentro de um grupo ou de um ambiente micro ou macro. Estamos constantemente nos relacionando e interagindo a todo momento, em qualquer lugar. Trocamos informações, experiências e percepções, sem nos dar conta das informações e mensagens subliminares que estamos passando.",
        references: "Não",
    },
    {
        id: 2,
        title: "Os 4Ps do Marketing",
        area: "Marketing",
        definition: "Também conhecido como \"Mix de Marketing\" são um conceito que resume os quatro pilares fundamentais para uma estratégia de marketing, todos eles começando pela letra P: produto, preço, praça e promoção.",
        objective: "Pessoal",
        description: "Com as respostas, é possível direcionar as ações da equipe de marketing para conseguir trabalhar de maneira efetiva com os potenciais clientes e conseguir reverter em vendas. Caso contrário, a empresa sofrerá para estabelecer um relacionamento e, consequentes, negócios.",
        references: "sim",
    },
    {
        id: 3,
        title: "React Native",
        area: "Tecnologias",
        definition: "Um Framework é um facilitador no desenvolvimento de diversas aplicações e, sem dúvida, sua utilização poupa tempo e custos para quem utiliza, pois de forma mais básica, é um conjunto de bibliotecas utilizadas para criar uma base, onde as aplicações são construídas, um otimizador de recursos",
        objective: "Pessoal",
        description: "É notável a crescente demanda do uso de aplicativos móveis nos últimos anos. Pensando nisso, diversas empresas desenvolvem suas soluções para facilitar a criação destes aplicativos. Com o React Native, o Facebook lançou uma solução incrível para o desenvolvimento multiplataforma utilizando apenas código Javascript, o que facilita (e muito) os desenvolvedores que já possuem conhecimento em desenvolvimento web e até os que não possuem, já que é um framework com alta curva de aprendizado.",
        references: "Sim",
    },
    {
        id: 4,
        title: "Lorem Ipsum Neque porro quisquam est qui dolorem",
        area: "Organização de projetos",
        definition: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        objective: "Pessoal",
        description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        references: "Não",
    },
    {
        id: 5,
        title: "Lorem Ipsum Neque porro quisquam est qui dolorem",
        area: "Administração",
        definition: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        objective: "Profissional",
        description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
        references: "Não",
    },
]
