import { StyleSheet, Dimensions } from "react-native";
const { height, width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center", justifyContent: "center" },
  headerContainer: {
    height: 90,
    backgroundColor: "#293241",
    borderBottomColor: "#293241",
  },
  headerText: {
    color: "#fff",
    fontSize: 25,
    paddingTop: 7,
    fontWeight: "bold",
  },
  bgImage: { height, width },
  bgImageFixed: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  scrollViewStyle: {
    backgroundColor: "transparent",
    marginBottom: 20,
  },
  body: { flex: 1, justifyContent: "center" },
  listItemContainer: { backgroundColor: "#fff", marginTop: 10 },
  listItemTitulo: { color: "#293241", fontSize: 25, fontWeight: "bold" },
  listItemSubtitulo: { color: "#293241", fontSize: 20 },
  login: { flex: 1, justifyContent: "center" },
  loginLogo: {
    height: 160,
    width: 160,
    borderRadius: 100,
    marginBottom: 20,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  loginBtn: { backgroundColor: "#293241", height: 45 },
  loginBtnContainer: { width: "75%", marginLeft: "12.5%" },
  registerBtn: { color: "#E37B09", fontSize: 18 },
  registerBtnContainer: { margin: 20, marginTop: 30 },
  input: { backgroundColor: "#fff", height: 45, width: "80%", paddingLeft: 15 },
  inputContainer: {
    width: "80%",
    marginVertical: 10,
    marginLeft: "10%",
  },
  form: { flex: 1, padding: 12, marginTop: 20 },
  formText: { color: "#fff", fontSize: 20, paddingLeft: 5, marginLeft: "10%" },
  formLabelText: { color: "#fff", fontSize: 20, fontWeight: "normal" },
  formSave: {
    width: 100,
  },
  formSaveBtn: {
    backgroundColor: "#293241",
  },
  formBack: {
    width: 100,
  },
  formBackBtn: { backgroundColor: "tomato" },
  formContainerBotoes: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: "5%",
  },
  formPicker: {
    height: 40,
    color: "#333",
    fontFamily: "sans-serif",
    fontSize: 40,
  },
  formPickerContainer: {
    backgroundColor: "#fff",
    width: "74%",
    marginLeft: "13%",
    margin: 10,
  },
  secaoTitulo: { fontSize: 40, fontWeight: "bold", color: "#E37B09" },
  semIdeiasText: {
    fontSize: 20,
    marginVertical: 20,
    marginHorizontal: 10,
    color: "#fff",
  },
  listContainer: { flex: 1, marginHorizontal: "5%" },
  mostraSenhaBtn: { backgroundColor: "#fff", height: 45 },
  tituloInput: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#000",
    textAlign: "left",
    marginLeft: 10,
  },
  botaoContainer: {
    marginTop: 25,
    marginBottom: 25,
    flexDirection: "row",
  },
  botaoSalveCancel: {
    height: 45,
    width: 95,
    marginLeft: 20,
    borderRadius: 5,
  },
  botaoaddIdeia: {
    position: "absolute",
    width: 48,
    height: 48,
    backgroundColor: "#1D1D1D",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    right: 25,
    bottom: 25,
    elevation: 2,
    zIndex: 9,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: {
      width: 1,
      height: 3,
    },
  },
  acoesLista: {
    position: "absolute",
    justifyContent: "space-between",
    flexDirection: "row",
    right: 10,
  },
  textBotaoSalveCancel: {
    color: "#FFFFFF",
    fontWeight: "bold",
    textAlign: "center",
    padding: 13,
    fontSize: 15,
  },
  lista: {
    backgroundColor: "#fff",
    marginTop: 10,
    borderRadius: 5,
    width: "92%",
    justifyContent: "center",
    padding: 5,
    marginRight: 8,
  },
  tituloIdeia: {
    fontSize: 17,
    color: "#127289",
    fontWeight: "700",
  },
  descIdeia: {
    fontSize: 14,
    width: "80%",
  },
  tituloExclusao: {
    fontSize: 19,
    margin: 8,
    textAlign: "center",
    fontWeight: "700",
    color: "#1281AB",
  },
  containerExclusao: {
    backgroundColor: "#FFFFFF",
    alignContent: "center",
    justifyContent: "center",
    borderRadius: 5,
    width: "90%",
    height: "30%",
    marginLeft: 14,
  },
});
